---
- name: make java-server.service
  blockinfile:
    dest: /lib/systemd/system/java-server.service
    block: |
      [Unit]
      Description=Chat Server Service
      After=network.target

      [Service]
      Type=simple
      User=root
      ExecStart=/home/user/java/jdk-18_linux-x64_bin.rpm/bin -Xmx1024M -Xms1024M -jar /home/user/local/java-api/server.jar nogui
      Restart=on-abort


      [Install]
      WantedBy=multi-user.target
    insertafter: EOF
    create: yes

- name: daemon-reload 
  command: systemctl daemon-reload

- name: enable myapp on start up
  command: systemctl enable java-server.service

- name: reloading java-server.service
  service:
    name: java-server.service
    state: restarted
