---
- name: make java-server.service
  blockinfile:
    dest: /lib/systemd/system/java-server.service
    block: |
      [Unit]
      Description=Chat Server Service
      After=network.target

      [Service]
      Type=simple
      User=root
      ExecStart=/usr/bin/java -Xmx1024M -Xms1024M -jar /home/user/java/server.jar nogui
      Restart=on-abort


      [Install]
      WantedBy=multi-user.target
    insertafter: EOF
    create: yes
    
- name: daemon-reload 
  command: systemctl daemon-reload

- name: enable myapp on start up
  command: systemctl enable java-hello-app.service

- name: reloading java-hello-app.service
  service:
    name: java-hello-app.service
    state: restarted
