---
- name: "Make Java directory"
  ansible.builtin.file:
    path: /home/user/java
    state: directory

- name: Download jre-8u333-linux-x64.rpm
  ansible.builtin.get_url:
    url: https://nexusrm.easlab.co.uk/repository/eas-hosted-bin/jdk-18_linux-x64_bin.rpm
    dest: /home/user/java/
    mode: '0777'
    validate_certs: no

- name: "Download Java Runtime"
  yum: 
    name: /home/user/java/jdk-18_linux-x64_bin.rpm
    state: present

